#theme = "hugo-lithium"
theme = "quanteda"
baseURL = "https://quanteda.org"
#baseURL = "http://127.0.0.1:7964"
languageCode = "en-gb"
title = "Quanteda Initiative"

# Enable comments by entering your Disqus shortname
disqusShortname = "quanteda"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-144616-23"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 2

[[menu.main]]
    name = "Projects"
    url  = "#"
    identifier = "projects"
    weight = 3
    
[[menu.main]]
    name = "quanteda"
    url  = "/quanteda/"
    parent = "projects"
    weight = 1
    
[[menu.main]]
    name = "readtext"
    url  = "http://readtext.quanteda.io/"
    parent = "projects"
    weight = 2
    
[[menu.main]]
    name = "spacyr"
    url  = "http://spacyr.quanteda.io/"
    parent = "projects"
    weight = 3
    
[[menu.main]]
    name = "stopwords"
    url  = "http://stopwords.quanteda.io/"
    parent = "projects"
    weight = 4

[[menu.main]]
    name = "Services"
    url  = "/services/"
    weight = 4
    
[[menu.main]]
    name = "News"
    url  = "/news/"
    weight = 5
    